# ---- begin snakebids boilerplate ----------------------------------------------

import snakebids
from snakebids import bids


configfile: "config/snakebids.yml"


# writes inputs_config.yml and updates config dict
config.update(
    snakebids.generate_inputs(
        bids_dir=config["bids_dir"],
        pybids_inputs=config["pybids_inputs"],
        derivatives=config["derivatives"],
        participant_label=config["participant_label"],
        exclude_participant_label=config["exclude_participant_label"],
        use_bids_inputs=False,
    )
)


# this adds constraints to the bids naming
wildcard_constraints:
    **snakebids.get_wildcard_constraints(config["pybids_inputs"]),


# ---- end snakebids boilerplate ------------------------------------------------

from pathlib import Path
from functools import partial

if config.get("dwi_dir"):
    print(f"Searching {config.get('dwi_dir')} for dwi and mask images...")


# Rules
include: "rules/freesurfer.smk"
include: "rules/zona_bb_subcortex.smk"
include: "rules/mrtpipelines.smk"


rule all:
    input:
        files=expand(
            rules.filtered_tck2connectome.output.sl_assignment,
            subject=config["input_lists"]["T1w"]["subject"],
        ),
        fs_tsv=str(
            Path(config["output_dir"]) / "freesurfer" / config["freesurfer"]["tsv"]
        ),
        zona_tsv=str(
            Path(config["output_dir"])
            / "zona_bb_subcortex"
            / config["zona_bb_subcortex"]["tsv"]
        ),
