#!/bin/bash
# Variables
subj=$1
njobs=$2
out_dir=$HOME/scratch/Zona/data/hcp1200_3T/hcp_test
localscratch=$SLURM_TMPDIR

SINGULARITY_NEUROGLIA=$HOME/singularity/khanlab_neuroglia-core_v1.3.0.img
SINGULARITY_MRT=$HOME/opt/singularity/mrtpipelines_0.1.6.sif
export SINGULARITYENV_OMP_NUM_THREADS=$njobs
export SINGULARITYENV_MKL_NUM_THREADS=$njobs

# Create subject specific directories on localscratch
mkdir -p $localscratch/$subj

# Processing
## Extract ROIs
echo "Getting precentral and brainstem ROIs..."
singularity exec $SINGULARITY_NEUROGLIA fslmaths $out_dir/derivatives/freesurfer/$subj/anat/${subj}_space-T1w_aparc+aseg.nii.gz -thr 1024 -uthr 1024 -bin $localscratch/${subj}/${subj}_space-T1w_hemi-L_desc-precentral_mask.nii.gz
singularity exec $SINGULARITY_NEUROGLIA fslmaths $out_dir/derivatives/freesurfer/$subj/anat/${subj}_space-T1w_aparc+aseg.nii.gz -thr 1022 -uthr 1022 -bin $localscratch/${subj}/${subj}_space-T1w_hemi-L_desc-postcentral_mask.nii.gz
singularity exec $SINGULARITY_NEUROGLIA fslmaths $localscratch/${subj}/${subj}_space-T1w_hemi-L_desc-precentral_mask.nii.gz -add $localscratch/${subj}/${subj}_space-T1w_hemi-L_desc-postcentral_mask.nii.gz $localscratch/$subj/${subj}_space-T1w_hemi-L_desc-central_mask.nii.gz

singularity exec $SINGULARITY_NEUROGLIA fslmaths $out_dir/derivatives/freesurfer/$subj/anat/${subj}_space-T1w_aparc+aseg.nii.gz -thr 2024 -uthr 2024 -bin $localscratch/${subj}/${subj}_space-T1w_hemi-R_desc-precentral_mask.nii.gz
singularity exec $SINGULARITY_NEUROGLIA fslmaths $out_dir/derivatives/freesurfer/$subj/anat/${subj}_space-T1w_aparc+aseg.nii.gz -thr 2022 -uthr 2022 -bin $localscratch/${subj}/${subj}_space-T1w_hemi-R_desc-postcentral_mask.nii.gz
singularity exec $SINGULARITY_NEUROGLIA fslmaths $localscratch/${subj}/${subj}_space-T1w_hemi-R_desc-precentral_mask.nii.gz -add $localscratch/${subj}/${subj}_space-T1w_hemi-R_desc-postcentral_mask.nii.gz $localscratch/$subj/${subj}_space-T1w_hemi-R_desc-central_mask.nii.gz

singularity exec $SINGULARITY_NEUROGLIA fslmaths $out_dir/derivatives/freesurfer/$subj/anat/${subj}_space-T1w_aparc+aseg.nii.gz -thr 16 -uthr 16 -bin $localscratch/${subj}/${subj}_space-T1w_desc-brainstem_mask.nii.gz

rm $localscratch/$subj/${subj}_space-T1w_hemi-*_desc-precentral_mask.nii.gz $localscratch/$subj/${subj}_space-T1w_hemi-*_desc-postcentral_mask.nii.gz 


## Initial tractography
echo "Generating initial tractography..."
# singularity exec $SINGULARITY_MRT dwi2fod -mask $out_dir/derivatives/mrtpipelines_0.1.6/mrtpipelines/$subj/dwi/${subj}_space-dwi_brainmask.mif -nthreads $njobs -shell 0,1000,2000,3000 msmt_csd $out_dir/derivatives/mrtpipelines_0.1.6/mrtpipelines/$subj/dwi/${subj}_space-dwi_dwi.mif /scratch/$USER/Zona/data/hcp1200_3T/deriv_common/avg_response/sub-HCPUR100_desc-avg_model-CSD_WMResp.txt $localscratch/$subj/${subj}_space-dwi_desc-avg_model-CSD_WMFOD.mif 

# singularity exec $SINGULARITY_MRT mtnormalise -nthreads $njobs -mask $out_dir/derivatives/mrtpipelines_0.1.6/mrtpipelines/$subj/dwi/${subj}_space-dwi_brainmask.mif -niter 15 -order 3 -value 0.282095 $localscratch/$subj/${subj}_space-dwi_desc-avg_model-CSD_WMFOD.mif $localscratch/$subj/${subj}_space-dwi_desc-avg_model-CSD_WMFODNorm.mif

for hemi in L R; do 
  singularity exec $SINGULARITY_MRT tckgen -algorithm iFOD2 -step 0.35 -nthreads 8 -include $localscratch/$subj/${subj}_space-T1w_hemi-${hemi}_desc-central_mask.nii.gz -include $localscratch/$subj/${subj}_space-T1w_desc-brainstem_mask.nii.gz -mask $out_dir/derivatives/mrtpipelines_0.1.6/mrtpipelines/$subj/dwi/${subj}_space-dwi_brainmask.mif -seed_image $out_dir/derivatives/mrtpipelines_0.1.6/mrtpipelines/$subj/dwi/${subj}_space-dwi_brainmask.mif -select 500 $out_dir/derivatives/mrtpipelines_0.1.6/mrtpipelines/$subj/response/${subj}_space-dwi_desc-avg_model-CSD_WMFODNorm.mif $localscratch/$subj/${subj}_space-dwi_hemi-${hemi}_desc-CST_tractography.tck 
done 

singularity exec $SINGULARITY_MRT tckedit $localscratch/$subj/${subj}_space-dwi_hemi-*_desc-CST_tractography.tck $localscratch/$subj/${subj}_space-dwi_desc-CST_tractography.tck

rm $localscratch/$subj/${subj}_space-dwi_hemi-*_desc-CST_tractography.tck


## Tractography cleanup
## Does not remove streamlines passing through other GM rois
echo "Grabbing streamlines that terminate within a 1.5mm radius of ROIs..."
singularity exec $SINGULARITY_MRT mrcalc -nthreads $njobs $localscratch/$subj/${subj}_space-T1w_hemi-L_desc-central_mask.nii.gz $localscratch/$subj/${subj}_space-T1w_hemi-R_desc-central_mask.nii.gz 2 -mult -add $localscratch/$subj/${subj}_space-T1w_desc-brainstem_mask.nii.gz 3 -mult -add $localscratch/$subj/${subj}_space-T1w_desc-combined_mask.nii.gz

singularity exec $SINGULARITY_MRT tck2connectome -nthreads $njobs -zero_diagonal -stat_edge sum -assignment_radial_search 1.5 -out_assignments $localscratch/$subj/${subj}_space-dwi_desc-CST_nodeassignment.txt -symmetric $localscratch/$subj/${subj}_space-dwi_desc-CST_tractography.tck $localscratch/$subj/${subj}_space-T1w_desc-combined_mask.nii.gz -

singularity exec $SINGULARITY_MRT connectome2tck -nthreads $njobs -nodes 1,2,3 -exclusive -files per_edge $localscratch/$subj/${subj}_space-dwi_desc-CST_tractography.tck $localscratch/$subj/${subj}_space-dwi_desc-CST_nodeassignment.txt $localscratch/$subj/${subj}_space-dwi_desc-from_


# Move output to subject folders
rsync -r $localscratch/$subj/${subj}_space-dwi_desc-from_1-3.tck $out_dir/derivatives/mrtpipelines_0.1.6/mrtpipelines/$subj/tractography
rsync -r $localscratch/$subj/${subj}_space-dwi_desc-from_2-3.tck $out_dir/derivatives/mrtpipelines_0.1.6/mrtpipelines/$subj/tractography